module.exports = {
  silent: false,
  packagePath: process.cwd(),
  tsConfigName: 'tsconfig.app',
  tsConfigOutName: 'tsconfig',
  tsConfigPath: './',
  tsConfigOutPath: './',
  jspm: require('jspm'),
  baseUrl: '.',
  noBackupTsConfig: false,
  noBackupWarning: false,
  backupOverwrite: false,
  backupPrefix: '',
  backupSuffix: '.backup',
};
